version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - VITE_WS_URL=wss://simulation.aaryareddy.com/ws/simulation
    restart: unless-stopped
    networks:
      - app_network
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - MAX_WORKERS=4
      - CORS_ORIGINS=["https://simulation.aaryareddy.com"]
      - HOST=0.0.0.0
      - PORT=8000
    restart: unless-stopped
    networks:
      - app_network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - app_network

networks:
  app_network:
    driver: bridge