version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_WS_URL=ws://simulation.aaryareddy.com/ws/simulation
    restart: unless-stopped
    networks:
      - app_network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - MAX_WORKERS=4
      - CORS_ORIGINS=["http://localhost", "https://simulation.aaryareddy.com"]
    restart: unless-stopped
    networks:
      - app_network
    # Remove direct port exposure if present
    # ports:
    #   - "8000:8000"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - app_network

networks:
  app_network:
    driver: bridge